/* eslint-disable */
/* prettier-ignore */
// @ts-nocheck
// Generated by unplugin-vue-components
// Read more: https://github.com/vuejs/core/pull/3399
export {}

declare module 'vue' {
    export interface GlobalComponents {
        AAvatar: typeof import('ant-design-vue/es')['Avatar'];
        ABadge: typeof import('ant-design-vue/es')['Badge'];
        ABreadcrumb: typeof import('ant-design-vue/es')['Breadcrumb'];
        AButton: typeof import('ant-design-vue/es')['Button'];
        AConfigProvider: typeof import('ant-design-vue/es')['ConfigProvider'];
        ADrawer: typeof import('ant-design-vue/es')['Drawer'];
        ADropdown: typeof import('ant-design-vue/es')['Dropdown'];
        AInputNumber: typeof import('ant-design-vue/es')['InputNumber'];
        ALayout: typeof import('ant-design-vue/es')['Layout'];
        ALayoutFooter: typeof import('ant-design-vue/es')['LayoutFooter'];
        ALayoutHeader: typeof import('ant-design-vue/es')['LayoutHeader'];
        ALayoutSider: typeof import('ant-design-vue/es')['LayoutSider'];
        AList: typeof import('ant-design-vue/es')['List'];
        AListItem: typeof import('ant-design-vue/es')['ListItem'];
        AListItemMeta: typeof import('ant-design-vue/es')['ListItemMeta'];
        AMenu: typeof import('ant-design-vue/es')['Menu'];
        AMenuDivider: typeof import('ant-design-vue/es')['MenuDivider'];
        AMenuItem: typeof import('ant-design-vue/es')['MenuItem'];
        APopconfirm: typeof import('ant-design-vue/es')['Popconfirm'];
        APopover: typeof import('ant-design-vue/es')['Popover'];
        AppDarkModeToggle: typeof import('./src/components/Application/src/AppDarkModeToggle.vue')['default'];
        AppLocalePicker: typeof import('./src/components/Application/src/AppLocalePicker.vue')['default'];
        AppLogo: typeof import('./src/components/Application/src/AppLogo.vue')['default'];
        AppProvider: typeof import('./src/components/Application/src/AppProvider.vue')['default'];
        ASelect: typeof import('ant-design-vue/es')['Select'];
        ASkeleton: typeof import('ant-design-vue/es')['Skeleton'];
        ASpace: typeof import('ant-design-vue/es')['Space'];
        ASpin: typeof import('ant-design-vue/es')['Spin'];
        AStyleProvider: typeof import('ant-design-vue/es')['StyleProvider'];
        ASubMenu: typeof import('ant-design-vue/es')['SubMenu'];
        ASwitch: typeof import('ant-design-vue/es')['Switch'];
        ATabPane: typeof import('ant-design-vue/es')['TabPane'];
        ATabs: typeof import('ant-design-vue/es')['Tabs'];
        ATag: typeof import('ant-design-vue/es')['Tag'];
        ATooltip: typeof import('ant-design-vue/es')['Tooltip'];
        ATypographyParagraph: typeof import('ant-design-vue/es')['TypographyParagraph'];
        BasicArrow: typeof import('./src/components/Basic/src/BasicArrow.vue')['default'];
        BasicDrawer: typeof import('./src/components/Drawer/src/BasicDrawer.vue')['default'];
        BasicHelp: typeof import('./src/components/Basic/src/BasicHelp.vue')['default'];
        BasicMenu: typeof import('./src/components/Menu/src/BasicMenu.vue')['default'];
        BasicMenuItem: typeof import('./src/components/Menu/src/components/BasicMenuItem.vue')['default'];
        BasicSubMenuItem: typeof import('./src/components/Menu/src/components/BasicSubMenuItem.vue')['default'];
        BasicTitle: typeof import('./src/components/Basic/src/BasicTitle.vue')['default'];
        CollapseContainer: typeof import('./src/components/Container/src/collapse/CollapseContainer.vue')['default'];
        CollapseHeader: typeof import('./src/components/Container/src/collapse/CollapseHeader.vue')['default'];
        CollapseTransition: typeof import('./src/components/Transition/src/CollapseTransition.vue')['default'];
        CountButton: typeof import('./src/components/CountDown/src/CountButton.vue')['default'];
        CountdownInput: typeof import('./src/components/CountDown/src/CountdownInput.vue')['default'];
        DrawerFooter: typeof import('./src/components/Drawer/src/components/DrawerFooter.vue')['default'];
        DrawerHeader: typeof import('./src/components/Drawer/src/components/DrawerHeader.vue')['default'];
        Dropdown: typeof import('./src/components/Dropdown/src/Dropdown.vue')['default'];
        Icon: typeof import('./src/components/Icon/src/Icon.vue')['default'];
        LazyContainer: typeof import('./src/components/Container/src/LazyContainer.vue')['default'];
        Loading: typeof import('./src/components/Loading/src/Loading.vue')['default'];
        Menu: typeof import('./src/components/SimpleMenu/src/components/Menu.vue')['default'];
        MenuCollapseTransition: typeof import('./src/components/SimpleMenu/src/components/MenuCollapseTransition.vue')['default'];
        MenuItem: typeof import('./src/components/SimpleMenu/src/components/MenuItem.vue')['default'];
        MenuItemContent: typeof import('./src/components/Menu/src/components/MenuItemContent.vue')['default'];
        RouterLink: typeof import('vue-router')['RouterLink'];
        RouterView: typeof import('vue-router')['RouterView'];
        Scrollbar: typeof import('./src/components/Scrollbar/src/Scrollbar.vue')['default'];
        ScrollContainer: typeof import('./src/components/Container/src/ScrollContainer.vue')['default'];
        SimpleMenu: typeof import('./src/components/SimpleMenu/src/SimpleMenu.vue')['default'];
        SimpleMenuTag: typeof import('./src/components/SimpleMenu/src/SimpleMenuTag.vue')['default'];
        SimpleSubMenu: typeof import('./src/components/SimpleMenu/src/SimpleSubMenu.vue')['default'];
        SubMenuItem: typeof import('./src/components/SimpleMenu/src/components/SubMenuItem.vue')['default'];
        SvgIcon: typeof import('./src/components/Icon/src/SvgIcon.vue')['default'];
    }
}
