#!/bin/sh
. "$(dirname "$0")/_/husky.sh"
. "$(dirname "$0")/common.sh"

[ -n "$CI" ] && exit 0

# 检查文件名
pnpm run lint:ls-lint

# 更改文件之前的格式
pnpm run lint:lint-staged

# pretty
pnpm run lint:lint-pretty

# style
# pnpm run lint:stylelint

